# Generated by Django 4.0.5 on 2022-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SAVE SOIL', max_length=255)),
                ('content', models.TextField()),
                ('author', models.TextField(default='Shyam Mistry')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(default='draft')),
                ('published', models.TextField()),
                ('slug', models.SlugField(default='save-soil')),
                ('topic', models.TextField()),
            ],
        ),
    ]
