# Generated by Django 4.0.5 on 2022-06-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Soil Importance', max_length=255)),
                ('slug', models.SlugField(default='soil-importance')),
            ],
        ),
    ]
