# Generated by Django 4.0.5 on 2022-07-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='save-soil'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='Soil Importance', max_length=100, unique=True),
        ),
    ]
